[package]
name = "pr02_cargo"
version = "0.1.0"
edition = "2021"
description = "Pluralsight demo publishing project"
license = "Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.8.4"